services:
  player_colony_database:
    container_name: otte_player_colony_database
    image: postgres:latest
    restart: always
    ports:
      - "8432:5432"
    env_file:
      - ../secrets/player_colony_db_secrets.env
    environment:
      - POSTGRES_DB=PlayerPersistenceAndAssets
    volumes:
      - ./db_creation_scripts/db_tables_player_colony.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./db_creation_scripts/db_functions_player_colony.sql:/docker-entrypoint-initdb.d/01_functions.sql
      - ../secrets/player_colony_db_additional_users.sql:/docker-entrypoint-initdb.d/02_player_colony_db_additional_users.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  language_database:
    container_name: otte_language_database
    image: postgres:latest
    restart: always
    ports:
      - "8433:5432"
    env_file: 
      - ../secrets/language_db_secrets.env
    environment:
      - POSTGRES_DB=OTTEInternationalizationCatalogues
    volumes:
      - ./db_creation_scripts/db_tables_language.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ../secrets/language_db_additional_users.sql:/docker-entrypoint-initdb.d/01_language_db_additional_users.sql
      - ./db_creation_scripts/db_functions_language.sql:/docker-entrypoint-initdb.d/02_db_functions_language.sql
      - ./db_creation_scripts/db_data_language.sql:/docker-entrypoint-initdb.d/03_db_data_language.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  otte_main_backend:
    build:
      context: .
      dockerfile: /dockerfiles/main_backend.dockerfile
    ports:
      - "8080:80"
    env_file:
      - ../secrets/main_backend_secrets.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # DATABASE CONNECTION INFORMATION
      # Duly note access credentials are stored in the /secrets folder
      - OTTE_LANGUAGE_DB_HOST=host.docker.internal
      - OTTE_LANGUAGE_DB_PORT=8433
      - OTTE_LANGUAGE_DB_NAME=OTTEInternationalizationCatalogues
      - OTTE_PLAYER_COLONY_DB_HOST=host.docker.internal
      - OTTE_PLAYER_COLONY_DB_PORT=8432
      - OTTE_PLAYER_COLONY_DB_NAME=player_persistence_and_assets
    depends_on:
      - player_colony_database
      - language_database
  