services:
  colony_asset_database:
    container_name: otte_colony_assets_database
    image: postgres:latest
    restart: always
    ports:
      - "8432:5432"
    env_file:
      - ../secrets/colony_assets_db_secrets.env
    environment:
      - POSTGRES_DB=ColonyAndAssets
    volumes:
      - ./db_creation_scripts/db_tables_colony_assets.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./db_creation_scripts/db_functions_colony_assets.sql:/docker-entrypoint-initdb.d/01_functions.sql
      - ../secrets/colony_assets_db_additional_users.sql:/docker-entrypoint-initdb.d/02_colony_assets_db_additional_users.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"] # Yes this gives a warning when running docker-compose up because the env var is not set, but it stops the log spam
      interval: 10s
      timeout: 5s
      retries: 5

  player_database:
    container_name: otte_player_database
    image: postgres:latest
    restart: always
    ports:
      - "8431:5432"
    env_file:
      - ../secrets/player_db_secrets.env
    environment:
      - POSTGRES_DB=PlayerPersistance
    volumes:
      - ./db_creation_scripts/db_tables_player.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./db_creation_scripts/db_functions_player.sql:/docker-entrypoint-initdb.d/01_functions.sql
      - ../secrets/player_db_additional_users.sql:/docker-entrypoint-initdb.d/02_player_db_additional_users.sql
      - ./db_creation_scripts/db_data_player.sql:/docker-entrypoint-initdb.d/03_player_db_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"] # Yes this gives a warning when running docker-compose up because the env var is not set, but it stops the log spam
      interval: 10s
      timeout: 5s
      retries: 5

  language_database:
    container_name: otte_language_database
    image: postgres:latest
    restart: always
    ports:
      - "8433:5432"
    env_file: 
      - ../secrets/language_db_secrets.env
    environment:
      - POSTGRES_DB=OTTEInternationalizationCatalogues
    volumes:
      - ./db_creation_scripts/db_tables_language.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ../secrets/language_db_additional_users.sql:/docker-entrypoint-initdb.d/01_language_db_additional_users.sql
      - ./db_creation_scripts/db_functions_language.sql:/docker-entrypoint-initdb.d/02_db_functions_language.sql
      - ./db_creation_scripts/db_data_language.sql:/docker-entrypoint-initdb.d/03_db_data_language.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"] # Yes this gives a warning when running docker-compose up because the env var is not set, but it stops the log spam
      interval: 10s
      timeout: 5s
      retries: 5

  multiplayer_backend:
    container_name: otte_multiplayer_backend
    build:
      context: "../../bsc-multiplayer-backend"
      dockerfile: "./Dockerfile"
    ports:
      - "8080:8080"
    env_file:
      - ../secrets/multiplayer_backend_secrets.env
    environment:
      - SERVICE_PORT=8080

  main_backend:
    container_name: otte_main_backend
    build:
      context: "../../BSC-Main-Backend"
      dockerfile: "./Dockerfile"
    ports:
      - "5386:5386"
    env_file:
      - ../secrets/main_backend_secrets.env
    environment:
      - SERVICE_PORT=5386
      # Multiplayer Backend Connection Information
      - MULTIPLAYER_BACKEND_HOST=host.docker.internal
      - MULTIPLAYER_BACKEND_PORT=5385

      # DATABASE CONNECTION INFORMATION
      # Duly note access credentials are stored in the /secrets folder
      - LANGUAGE_DB_HOST=host.docker.internal
      - LANGUAGE_DB_PORT=8433
      - LANGUAGE_DB_NAME=OTTEInternationalizationCatalogues

      - COLONY_ASSET_DB_HOST=host.docker.internal
      - COLONY_ASSET_DB_PORT=8432
      - COLONY_ASSET_DB_NAME=ColonyAndAssets

      - PLAYER_DB_HOST=host.docker.internal
      - PLAYER_DB_PORT=8431
      - PLAYER_DB_NAME=PlayerPersistance
    depends_on:
      - colony_asset_database
      - language_database
      - player_database
      - multiplayer_backend
  
  