services:
  player_colony_database:
    container_name: otte_player_colony_database
    image: postgres:latest
    restart: always
    ports:
      - "8432:5432"
    environment:
      - POSTGRES_PASSWORD=0tt3M41nB4ck3ndP4ssw0rd!
      - POSTGRES_USER=OTTE_MAIN_BACKEND
      - POSTGRES_DB=PlayerPersistenceAndAssets
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db_creation_scripts/db_creation_player_colony_database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  language_database:
    container_name: otte_language_database
    image: postgres:latest
    restart: always
    ports:
      - "8433:5432"
    environment:
      - POSTGRES_PASSWORD=0tt3M41nB4ck3ndP4ssw0rd!
      - POSTGRES_USER=OTTE_MAIN_BACKEND
      - POSTGRES_DB=OTTEInternationalizationCatalogues
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db_creation_scripts/db_creation_player_colony_database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  otte_main_backend:
    build:
      context: .
      dockerfile: /dockerfiles/main_backend.dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - OTTE_LANGUAGE_DB_DSN="host.docker.internal 8433, OTTE_MAIN_BACKEND 0tt3M41nB4ck3ndP4ssw0rd!, OTTEInternationalizationCatalogues"
      - OTTE_PLAYER_COLONY_DB_DSN="host.docker.internal 8432, OTTE_MAIN_BACKEND 0tt3M41nB4ck3ndP4ssw0rd!, PlayerPersistenceAndAssets"
    depends_on:
      - player_colony_database
      - language_database
  