services:
  player_colony_database:
    container_name: otte_player_colony_database
    image: postgres:latest
    restart: always
    ports:
      - "8432:5432"
    environment:
      - POSTGRES_PASSWORD=0tt3M41nB4ck3ndP4ssw0rd!
      - POSTGRES_USER=OTTE_MAIN_BACKEND
      - POSTGRES_DB=PlayerPersistenceAndAssets
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  language_database:
    container_name: otte_language_database
    image: postgres:latest
    restart: always
    ports:
      - "8433:5432"
    environment:
      - POSTGRES_PASSWORD=0tt3M41nB4ck3ndP4ssw0rd!
      - POSTGRES_USER=OTTE_MAIN_BACKEND
      - POSTGRES_DB=OTTEInternationalizationCatalogues
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5